version: "3.8"

services:
  postgres:
    container_name: testing-system-db
    platform: linux/amd64
    image: soulmate1/testing-system-db:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "000123000"
      POSTGRES_DB: testing-system-db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    container_name: testing-system-api
    restart: always
    platform: linux/amd64
    image: soulmate1/testing-system-api:latest
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: "000123000"
      DB_NAME: testing-system-db
    ports:
      - "25504:25501"

  frontend:
    container_name: testing-system-web
    restart: always
    platform: linux/amd64
    image: soulmate1/testing-system-web:latest
    ports:
      - "3000:81"
    depends_on:
      - backend

volumes:
  postgres_data:
